# Generated by Django 3.0.8 on 2020-07-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
